name: fi
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cmake
  - python 
  - jinja2
  - scikit-learn
  - numpy
  - pytorch==1.9.1 
  - torchvision==0.10.1 
  - torchaudio==0.9.1
  - cudatoolkit=10.2
  - pytorch-lightning=1.6.1
  - xgboost
  - pip
  - pip:
    - onnx
    - cvxpy
    - onnxruntime 
    - pip install git+https://github.com/sbuschjaeger/PyPruning.git
    - -e file:. 