name: Running neural network tests

on:
  push:
    branches: [main]

jobs:
  test-nn:
    runs-on: ubuntu-latest
    container: pytorchlightning/pytorch_lightning:1.6.1-py3.9-torch1.9
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
            pip install .
      
      - name: Test MLP inference 
        run: | 
            cd $GITHUB_WORKSPACE
            mkdir -p $outpath
            cd tests
            python3 test_mlp.py --dataset $data --outpath $outpath --modelname $modelname 
        env:
          data: mnist
          outpath: /tmp/fastinference/SimpleMLP
          modelname: SimpleMLP
      
      - name: Test binarized MLP inference 
        run: | 
            cd $GITHUB_WORKSPACE
            mkdir -p $outpath
            cd tests
            python3 test_mlp.py --dataset $data --outpath $outpath --modelname $modelname --binarize 
        env:
          data: mnist
          outpath: /tmp/fastinference/SimpleMLP
          modelname: SimpleMLP

      - name: Test CNN inference 
        run: | 
            cd $GITHUB_WORKSPACE
            mkdir -p $outpath
            cd tests
            python3 test_cnn.py --dataset $data --outpath $outpath --modelname $modelname 
        env:
          data: mnist
          outpath: /tmp/fastinference/SimpleCNN
          modelname: SimpleCNN

      - name: Test binarize CNN inference 
        run: | 
            cd $GITHUB_WORKSPACE
            mkdir -p $outpath
            cd tests
            python3 test_cnn.py --dataset $data --outpath $outpath --modelname $modelname --binarize 
        env:
          data: mnist
          outpath: /tmp/fastinference/SimpleCNN
          modelname: SimpleCNN